$axure.loadCurrentPage({
  "url":"帐号管理-添加银行卡1.html",
  "generationDate":new Date(1435069089887.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79e99c1fa016465c9015769cf3a937d6",
    "type":"Axure:Page",
    "name":"帐号管理-添加银行卡1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0177808f7404a4dbc503e207aa3a857",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":1392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4466a15c964af4a6a7e9eff65698db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1400,
                  "height":1392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u0.jpg"}},
{
          "id":"546756cd740148a29b4d8d1278327bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":162},
            "size":{
              "width":930,
              "height":798},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fbce2e8fe441ba9312df3eebbaa45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":162},
                "size":{
                  "width":930,
                  "height":798},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u2.png"}},
{
          "id":"b39dbc37ef7144e5a4547fad46636b94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":191},
            "size":{
              "width":905,
              "height":558}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4129b6ed2d0b46e1b5627fc7ee87a206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":191},
                "size":{
                  "width":905,
                  "height":558}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-添加银行卡1/u4.png"}},
{
          "id":"eccb1ac40350494197df78501b99d706",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":82},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7067488d658a44a280c19a5ac2783fe5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"2f85097d6c404886a95c08fe8373924b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":235},
            "size":{
              "width":425,
              "height":560}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039d2aed29764759ab5f16c5f7a972d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":235},
                "size":{
                  "width":425,
                  "height":560}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-添加银行卡1/u7.png"}},
{
          "id":"824178345f05444c84cef0c52f2bc19c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":730},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-添加银行卡2",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-添加银行卡2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5304089bb7644fcdb18bffc320b7c22a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
},
  "objectPaths":{
    "c0177808f7404a4dbc503e207aa3a857":{
      "scriptId":"u0"},
    "1c4466a15c964af4a6a7e9eff65698db":{
      "scriptId":"u1"},
    "546756cd740148a29b4d8d1278327bf4":{
      "scriptId":"u2"},
    "94fbce2e8fe441ba9312df3eebbaa45a":{
      "scriptId":"u3"},
    "b39dbc37ef7144e5a4547fad46636b94":{
      "scriptId":"u4"},
    "4129b6ed2d0b46e1b5627fc7ee87a206":{
      "scriptId":"u5"},
    "eccb1ac40350494197df78501b99d706":{
      "scriptId":"u6"},
    "2f85097d6c404886a95c08fe8373924b":{
      "scriptId":"u7"},
    "039d2aed29764759ab5f16c5f7a972d0":{
      "scriptId":"u8"},
    "824178345f05444c84cef0c52f2bc19c":{
      "scriptId":"u9"}}});