$axure.loadCurrentPage({
  "url":"充值.html",
  "generationDate":new Date(1435069090002.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d5ef5c7f1559436180cf58fd21fa4727",
    "type":"Axure:Page",
    "name":"充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a88cca3c919490db6f3a1d3d9935c6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":1},
            "size":{
              "width":419,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06efcf791f9a456497e4756b35f59e24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":1},
                "size":{
                  "width":419,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"9bcb7ba49ce042acbdbf5112ed5c9587",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":1},
            "size":{
              "width":419,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8f384f472848ee99dd36a21f85f8a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":1},
                "size":{
                  "width":419,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"8e3c9a58978f4dac8c48a7fd3c7b4afb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF7C828E},
            "location":{
              "x":0,
              "y":790},
            "size":{
              "width":1300,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7C828E}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e2945d4cd41478f881d4e5e8deb7e98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7C828E},
                "location":{
                  "x":0,
                  "y":790},
                "size":{
                  "width":1300,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7C828E}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"ba9fb09e39154a4e84c6a8c3350cdd94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":640},
            "size":{
              "width":756,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbf94c3c863455785fa78520e0af473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":640},
                "size":{
                  "width":756,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u6.png"}},
{
          "id":"75b116a10180425587188a1a41a9c9a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":160},
            "size":{
              "width":250,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b6ebaca5774d068af00a74bb227642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":160},
                "size":{
                  "width":250,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u8.png"}},
{
          "id":"42795a7f398748f6ae27e543740d6d62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":165},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0acb3da9bda4c6c8d379834474f64d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":165},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"083d1101720f48d3b20d4f9bf9f2d39f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":790},
            "size":{
              "width":1169,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a73b74d9e124fde898d1190f5112b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":790},
                "size":{
                  "width":1169,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u12.png"}},
{
          "id":"9df3519276de45e8bb6c79f910fecb6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":790},
            "size":{
              "width":1169,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5130e66387244134baa74759b17d8f34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":790},
                "size":{
                  "width":1169,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u12.png"}},
{
          "id":"c6ec2b91967f4cd7bb11479aa0188a37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":2},
            "size":{
              "width":972,
              "height":715}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de0c3f84337c435fb7454b92c29b12e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":2},
                "size":{
                  "width":972,
                  "height":715}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u16.png"}},
{
          "id":"c22ca2ca0d5646d8bc9442b4f6ad18fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":460},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c7ba2dddc145c2b2dac02d5c484798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":460},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u18.png"}},
{
          "id":"37467b41755d40e3a715820e2eb694a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":516,
              "y":468},
            "size":{
              "width":77,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cbeb382fc4a49dabc40c36dd787abc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":516,
                  "y":468},
                "size":{
                  "width":77,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03e5ec07ccd4402482e2270b7e22d552",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":35},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79df5d5692f84eba917370a7bfd473b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":35},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u22.png"}},
{
          "id":"0a805fe688d0422e9fd673ca4bc191e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":42},
            "size":{
              "width":85,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7bafb8981b47c1a3f15b6806344e85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":42},
                "size":{
                  "width":85,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d46b2c2b0cd4df794e943e17f9bd28b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF5C739D},
            "location":{
              "x":1053,
              "y":7},
            "size":{
              "width":200,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C739D}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69522ddd75344d6cbda3365f814badbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5C739D},
                "location":{
                  "x":1053,
                  "y":7},
                "size":{
                  "width":200,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C739D}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u26.png"}},
{
          "id":"2b2cb1524886414e9b2528d662e9e61a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE4E4E4},
            "location":{
              "x":1104,
              "y":10},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a07a0b4c759a4d9eb202ee69e6b7aba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE4E4E4},
                "location":{
                  "x":1104,
                  "y":10},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a88cca3c919490db6f3a1d3d9935c6a":{
      "scriptId":"u0"},
    "06efcf791f9a456497e4756b35f59e24":{
      "scriptId":"u1"},
    "9bcb7ba49ce042acbdbf5112ed5c9587":{
      "scriptId":"u2"},
    "9c8f384f472848ee99dd36a21f85f8a0":{
      "scriptId":"u3"},
    "8e3c9a58978f4dac8c48a7fd3c7b4afb":{
      "scriptId":"u4"},
    "5e2945d4cd41478f881d4e5e8deb7e98":{
      "scriptId":"u5"},
    "ba9fb09e39154a4e84c6a8c3350cdd94":{
      "scriptId":"u6"},
    "bcbf94c3c863455785fa78520e0af473":{
      "scriptId":"u7"},
    "75b116a10180425587188a1a41a9c9a8":{
      "scriptId":"u8"},
    "d5b6ebaca5774d068af00a74bb227642":{
      "scriptId":"u9"},
    "42795a7f398748f6ae27e543740d6d62":{
      "scriptId":"u10"},
    "a0acb3da9bda4c6c8d379834474f64d8":{
      "scriptId":"u11"},
    "083d1101720f48d3b20d4f9bf9f2d39f":{
      "scriptId":"u12"},
    "1a73b74d9e124fde898d1190f5112b60":{
      "scriptId":"u13"},
    "9df3519276de45e8bb6c79f910fecb6a":{
      "scriptId":"u14"},
    "5130e66387244134baa74759b17d8f34":{
      "scriptId":"u15"},
    "c6ec2b91967f4cd7bb11479aa0188a37":{
      "scriptId":"u16"},
    "de0c3f84337c435fb7454b92c29b12e1":{
      "scriptId":"u17"},
    "c22ca2ca0d5646d8bc9442b4f6ad18fc":{
      "scriptId":"u18"},
    "61c7ba2dddc145c2b2dac02d5c484798":{
      "scriptId":"u19"},
    "37467b41755d40e3a715820e2eb694a7":{
      "scriptId":"u20"},
    "3cbeb382fc4a49dabc40c36dd787abc9":{
      "scriptId":"u21"},
    "03e5ec07ccd4402482e2270b7e22d552":{
      "scriptId":"u22"},
    "79df5d5692f84eba917370a7bfd473b4":{
      "scriptId":"u23"},
    "0a805fe688d0422e9fd673ca4bc191e4":{
      "scriptId":"u24"},
    "4f7bafb8981b47c1a3f15b6806344e85":{
      "scriptId":"u25"},
    "8d46b2c2b0cd4df794e943e17f9bd28b":{
      "scriptId":"u26"},
    "69522ddd75344d6cbda3365f814badbe":{
      "scriptId":"u27"},
    "2b2cb1524886414e9b2528d662e9e61a":{
      "scriptId":"u28"},
    "a07a0b4c759a4d9eb202ee69e6b7aba7":{
      "scriptId":"u29"}}});