$axure.loadCurrentPage({
  "url":"帐号管理.html",
  "generationDate":new Date(1435069089533.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da5147c53eea4b88a48c642cf3d166ef",
    "type":"Axure:Page",
    "name":"帐号管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd9dd364ce7041c39c1849e6181749f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":1392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f6ccd91d324967a5b469902daed714",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1400,
                  "height":1392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u0.jpg"}},
{
          "id":"546756cd740148a29b4d8d1278327bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":162},
            "size":{
              "width":930,
              "height":798},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fbce2e8fe441ba9312df3eebbaa45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":162},
                "size":{
                  "width":930,
                  "height":798},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u2.png"}},
{
          "id":"e6fd6b43c85b4d3fb84ac73423abc56d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":181},
            "size":{
              "width":918,
              "height":486}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fb1385ca8624cfabc3b9c761d010563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":181},
                "size":{
                  "width":918,
                  "height":486}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理/u4.png"}},
{
          "id":"309d590cb7794e16939b5eeefc1f6aba",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":981,
              "y":428},
            "size":{
              "width":179,
              "height":112}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-添加银行卡1",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-添加银行卡1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"37c626f656424628a8da28e24fa2e92f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"ef491450746a4dbd9b13c30a4de9ef5d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":505},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-添加银行卡1",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-添加银行卡1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1f09a9104f9d48748a496c56968b9d70",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"609662e508154c06bacc91ada8e5fa0c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":82},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cdf8fdee91e04ad08cfd3956c678bce9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"457445c599604f0c90fad7395b80483f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":517,
              "y":300},
            "size":{
              "width":53,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0308a1ed69fb401facda0684cf7d298a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":517,
                  "y":300},
                "size":{
                  "width":53,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u9.png"}},
{
          "id":"846b9f4b34994b928c4b5fdf64787921",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":523,
              "y":303},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f84eee695374d34bf4c0f6f1559a89e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":523,
                  "y":303},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bd9dd364ce7041c39c1849e6181749f7":{
      "scriptId":"u0"},
    "14f6ccd91d324967a5b469902daed714":{
      "scriptId":"u1"},
    "546756cd740148a29b4d8d1278327bf4":{
      "scriptId":"u2"},
    "94fbce2e8fe441ba9312df3eebbaa45a":{
      "scriptId":"u3"},
    "e6fd6b43c85b4d3fb84ac73423abc56d":{
      "scriptId":"u4"},
    "5fb1385ca8624cfabc3b9c761d010563":{
      "scriptId":"u5"},
    "309d590cb7794e16939b5eeefc1f6aba":{
      "scriptId":"u6"},
    "ef491450746a4dbd9b13c30a4de9ef5d":{
      "scriptId":"u7"},
    "609662e508154c06bacc91ada8e5fa0c":{
      "scriptId":"u8"},
    "457445c599604f0c90fad7395b80483f":{
      "scriptId":"u9"},
    "0308a1ed69fb401facda0684cf7d298a":{
      "scriptId":"u10"},
    "846b9f4b34994b928c4b5fdf64787921":{
      "scriptId":"u11"},
    "1f84eee695374d34bf4c0f6f1559a89e":{
      "scriptId":"u12"}}});