$axure.loadCurrentPage({
  "url":"帐号管理-添加银行卡2.html",
  "generationDate":new Date(1435069089951.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd5e4ec7a5574dd29cfafab552f8a068",
    "type":"Axure:Page",
    "name":"帐号管理-添加银行卡2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7e757efe56454de4905e6cb93a9469b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":1392},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF348DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a6f5cc5159406184d4302918275d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1400,
                  "height":1392},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF348DDA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u0.jpg"}},
{
          "id":"546756cd740148a29b4d8d1278327bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":162},
            "size":{
              "width":930,
              "height":798},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fbce2e8fe441ba9312df3eebbaa45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":162},
                "size":{
                  "width":930,
                  "height":798},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u2.png"}},
{
          "id":"934111a74b6d40218edf4b972376a604",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":647.5,
              "y":326},
            "size":{
              "width":375,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea6a8bacc244ac48eac292e571a533a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647.5,
                  "y":326},
                "size":{
                  "width":375,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-添加银行卡2/u4.png"}},
{
          "id":"51182767f65647959a79ff69d3e3a39b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":413},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a45c6d5161ae4add866c4bc8d646bf08",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"ec7b9c975c8347aeadfed000dc9b5471",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":82},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9178cfdb605047d787225348eb4eea02",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
},
  "objectPaths":{
    "7e757efe56454de4905e6cb93a9469b4":{
      "scriptId":"u0"},
    "84a6f5cc5159406184d4302918275d91":{
      "scriptId":"u1"},
    "546756cd740148a29b4d8d1278327bf4":{
      "scriptId":"u2"},
    "94fbce2e8fe441ba9312df3eebbaa45a":{
      "scriptId":"u3"},
    "934111a74b6d40218edf4b972376a604":{
      "scriptId":"u4"},
    "cea6a8bacc244ac48eac292e571a533a":{
      "scriptId":"u5"},
    "51182767f65647959a79ff69d3e3a39b":{
      "scriptId":"u6"},
    "ec7b9c975c8347aeadfed000dc9b5471":{
      "scriptId":"u7"}}});