$axure.loadCurrentPage({
  "url":"帐号管理-验证2.html",
  "generationDate":new Date(1435069089736.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7404631dd90f4fbbb2effae8cc9c6ca8",
    "type":"Axure:Page",
    "name":"帐号管理-验证2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d43897a94b644e529a6f9aeed4932ca6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":1392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"defe0e6e16e641c6b293ccacc520e78c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1400,
                  "height":1392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u0.jpg"}},
{
          "id":"546756cd740148a29b4d8d1278327bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":162},
            "size":{
              "width":930,
              "height":898},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fbce2e8fe441ba9312df3eebbaa45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":162},
                "size":{
                  "width":930,
                  "height":898},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u2.png"}},
{
          "id":"d8168b4812164e5e93dc58881441ab32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":384,
              "y":182},
            "size":{
              "width":886,
              "height":847}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c92fdd10bcb47b2aa21b123bc8f982b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":384,
                  "y":182},
                "size":{
                  "width":886,
                  "height":847}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u4.png"}},
{
          "id":"b7b7e10d20ad4183a9c717b9cc76fa0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":1060},
            "size":{
              "width":367,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c4799453594d6d86e4207b3babdfe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":1060},
                "size":{
                  "width":367,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u6.png"}},
{
          "id":"efe165e177614a8588ebe1a3659eb28e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":930},
            "size":{
              "width":295,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"249082f4b2d843e0acb66d26dc00f82f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":83,
                  "y":930},
                "size":{
                  "width":295,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u8.png"}},
{
          "id":"fd2e28cd0d604727ab63e078eb33acc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":383,
              "y":178},
            "size":{
              "width":887,
              "height":851}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c83f59747d334b62904f9935cf6b6335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":383,
                  "y":178},
                "size":{
                  "width":887,
                  "height":851}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u10.png"}},
{
          "id":"b17ffe5dfb954a818a81ca3d85ee6d69",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":82},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6853f1c513b74cc78f75274b9a8ee85d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"e30c20dc7c624d1080140e69f56eb8a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":960},
            "size":{
              "width":870,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce50753b66284ba78341683169bfab59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":960},
                "size":{
                  "width":870,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u13.png"}},
{
          "id":"79ed13ced7094053bfe12349f4780abf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":499},
            "size":{
              "width":503,
              "height":544}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8509014447e9410a8ee31f84a38553fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":499},
                "size":{
                  "width":503,
                  "height":544}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-验证2/u15.png"}},
{
          "id":"dcf7b650d91642ac9f1b5a2c4929e751",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":990},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-验证3",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-验证3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5403380482a34d63ad134b40268573e9",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]}]}},
  "masters":{
},
  "objectPaths":{
    "d43897a94b644e529a6f9aeed4932ca6":{
      "scriptId":"u0"},
    "defe0e6e16e641c6b293ccacc520e78c":{
      "scriptId":"u1"},
    "546756cd740148a29b4d8d1278327bf4":{
      "scriptId":"u2"},
    "94fbce2e8fe441ba9312df3eebbaa45a":{
      "scriptId":"u3"},
    "d8168b4812164e5e93dc58881441ab32":{
      "scriptId":"u4"},
    "8c92fdd10bcb47b2aa21b123bc8f982b":{
      "scriptId":"u5"},
    "b7b7e10d20ad4183a9c717b9cc76fa0a":{
      "scriptId":"u6"},
    "e9c4799453594d6d86e4207b3babdfe2":{
      "scriptId":"u7"},
    "efe165e177614a8588ebe1a3659eb28e":{
      "scriptId":"u8"},
    "249082f4b2d843e0acb66d26dc00f82f":{
      "scriptId":"u9"},
    "fd2e28cd0d604727ab63e078eb33acc5":{
      "scriptId":"u10"},
    "c83f59747d334b62904f9935cf6b6335":{
      "scriptId":"u11"},
    "b17ffe5dfb954a818a81ca3d85ee6d69":{
      "scriptId":"u12"},
    "e30c20dc7c624d1080140e69f56eb8a5":{
      "scriptId":"u13"},
    "ce50753b66284ba78341683169bfab59":{
      "scriptId":"u14"},
    "79ed13ced7094053bfe12349f4780abf":{
      "scriptId":"u15"},
    "8509014447e9410a8ee31f84a38553fa":{
      "scriptId":"u16"},
    "dcf7b650d91642ac9f1b5a2c4929e751":{
      "scriptId":"u17"}}});