$axure.loadCurrentPage({
  "url":"帐号管理-待验证.html",
  "generationDate":new Date(1435069089434.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"289a16c805b04ab29f13bb2029182486",
    "type":"Axure:Page",
    "name":"帐号管理-待验证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"17e940f669bb46508ef304d2d7286151",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":1392}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42338fff185e4e5ab6fdf6030fc96e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1400,
                  "height":1392}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u0.jpg"}},
{
          "id":"546756cd740148a29b4d8d1278327bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":162},
            "size":{
              "width":930,
              "height":798},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94fbce2e8fe441ba9312df3eebbaa45a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":162},
                "size":{
                  "width":930,
                  "height":798},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u2.png"}},
{
          "id":"cc539d4d1612411fa5aa5386d0939dbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":176},
            "size":{
              "width":908,
              "height":551}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cbc02cfaa9549039608479d0fa3e962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":176},
                "size":{
                  "width":908,
                  "height":551}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u4.png"}},
{
          "id":"8736b2a9685c4f58858b86a013722116",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":657,
              "y":197},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-验证1",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-验证1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"358204be3e334dff82217e1b1165c100",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"11f37afd31e342ca9c5560bd0d852d7c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":500},
            "size":{
              "width":176,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理-验证1",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理-验证1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2f6649b399d742f8a5ead461c30467aa",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"1c68ad07449044b58480bd0ffd7d1dee",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1190,
              "y":82},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dc7bafbeae1d455da48428fc1bb7505c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"723cecadb27d487781c240ba13253e8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":370},
            "size":{
              "width":53,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49a7c2b934924dfba008373b0e99b14d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":370},
                "size":{
                  "width":53,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帐号管理-待验证/u9.png"}},
{
          "id":"6ff17e50c6e64d3fa1a0f5a598f6440f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":521,
              "y":373},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48765075a2c4baf9abf6f9cac7f6e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":521,
                  "y":373},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "17e940f669bb46508ef304d2d7286151":{
      "scriptId":"u0"},
    "42338fff185e4e5ab6fdf6030fc96e5c":{
      "scriptId":"u1"},
    "546756cd740148a29b4d8d1278327bf4":{
      "scriptId":"u2"},
    "94fbce2e8fe441ba9312df3eebbaa45a":{
      "scriptId":"u3"},
    "cc539d4d1612411fa5aa5386d0939dbe":{
      "scriptId":"u4"},
    "2cbc02cfaa9549039608479d0fa3e962":{
      "scriptId":"u5"},
    "8736b2a9685c4f58858b86a013722116":{
      "scriptId":"u6"},
    "11f37afd31e342ca9c5560bd0d852d7c":{
      "scriptId":"u7"},
    "1c68ad07449044b58480bd0ffd7d1dee":{
      "scriptId":"u8"},
    "723cecadb27d487781c240ba13253e8e":{
      "scriptId":"u9"},
    "49a7c2b934924dfba008373b0e99b14d":{
      "scriptId":"u10"},
    "6ff17e50c6e64d3fa1a0f5a598f6440f":{
      "scriptId":"u11"},
    "a48765075a2c4baf9abf6f9cac7f6e6a":{
      "scriptId":"u12"}}});