$axure.loadCurrentPage({
  "url":"交易.html",
  "generationDate":new Date(1435069090058.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"372f87ac9424418f9182ca7920ddb78b",
    "type":"Axure:Page",
    "name":"交易",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"98775d617ab64491ae1a1189b7a59a0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":419,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7960a0a493b4e29bbe2597e6379c283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":419,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"fd1732db71f841b5852eaecf120a062c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":861,
              "y":1},
            "size":{
              "width":419,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0056328106de439bafc6fc190683c479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":861,
                  "y":1},
                "size":{
                  "width":419,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u0.png"}},
{
          "id":"f4fd572877ab4513b2a9d32d737d1d5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":640},
            "size":{
              "width":756,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef2efd34a45a4d7f877411a2d5da9dbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":640},
                "size":{
                  "width":756,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u6.png"}},
{
          "id":"7a3457d732b946838b453b4a7a1ebdba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":2},
            "size":{
              "width":975,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72504820efc345058994660305770843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":2},
                "size":{
                  "width":975,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易/u6.png"}},
{
          "id":"2ed9088e421d46a5aa56d928cd0c9241",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":160},
            "size":{
              "width":200,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"193d6495b10146a78949f1cb8cb09d60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":160},
                "size":{
                  "width":200,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易/u8.png"}},
{
          "id":"2420aca47f6545cfba08e6147e6a8f54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":165},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f0a99d2a81492483704db23bd54a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":165},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cfa08b0dbee4dc0b197fa4e4d453d50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":110},
            "size":{
              "width":557,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0cd48ea484643eb8d6b564d1bc7153f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":110},
                "size":{
                  "width":557,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易/u12.png"}},
{
          "id":"f02d58ef83dc4474906c440776a4fc22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":203,
              "y":133},
            "size":{
              "width":519,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4b2ba6105940ef80bc82fd86968700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":203,
                  "y":133},
                "size":{
                  "width":519,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d3b42d36da0446b876afde0e691bc2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":185},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58dd62b474dc4c20837d8cd714969cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":185},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd604b529aec488b81ddb37617293c08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF7C828E},
            "location":{
              "x":0,
              "y":790},
            "size":{
              "width":1300,
              "height":57},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF7C828E}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e851f1c4e7b4809a25d0a1d8bd11db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7C828E},
                "location":{
                  "x":0,
                  "y":790},
                "size":{
                  "width":1300,
                  "height":57},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF7C828E}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"2d7ac7367e3d49ce99c73b2639a1ca42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":87.5,
              "y":790},
            "size":{
              "width":1169,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65746a67035a46f0a3d5821f303ffdcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87.5,
                  "y":790},
                "size":{
                  "width":1169,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u12.png"}},
{
          "id":"d6522633fec9444d82eae65f10a9c395",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":2},
            "size":{
              "width":975,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a737f946347e40638d5e26e101a19aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":2},
                "size":{
                  "width":975,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易/u6.png"}},
{
          "id":"ff63bcd8f88149709a33e049255c979b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF5C739D},
            "location":{
              "x":100,
              "y":40},
            "size":{
              "width":200,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C739D}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9193413482844d529265a054983beb94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5C739D},
                "location":{
                  "x":100,
                  "y":40},
                "size":{
                  "width":200,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C739D}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u22.png"}},
{
          "id":"a5e9b47738aa4947a88c05f1cbcff4a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":42},
            "size":{
              "width":85,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5507151e97446b8f0328b6d86264eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":42},
                "size":{
                  "width":85,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9efdd34cf84d0a8c1a8d166d4b0540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF5C739D},
            "location":{
              "x":1053,
              "y":7},
            "size":{
              "width":200,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF5C739D}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9560dec3490d472d9960a83290d680c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF5C739D},
                "location":{
                  "x":1053,
                  "y":7},
                "size":{
                  "width":200,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF5C739D}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u26.png"}},
{
          "id":"6ebc27bff2bf44b3a24b911581670f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE4E4E4},
            "location":{
              "x":1104,
              "y":10},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acfd328d9e4a4addbf608d690ea084bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE4E4E4},
                "location":{
                  "x":1104,
                  "y":10},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 帐号管理",
                      "target":{
                        "targetType":"page",
                        "url":"帐号管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "98775d617ab64491ae1a1189b7a59a0a":{
      "scriptId":"u0"},
    "b7960a0a493b4e29bbe2597e6379c283":{
      "scriptId":"u1"},
    "fd1732db71f841b5852eaecf120a062c":{
      "scriptId":"u2"},
    "0056328106de439bafc6fc190683c479":{
      "scriptId":"u3"},
    "f4fd572877ab4513b2a9d32d737d1d5f":{
      "scriptId":"u4"},
    "ef2efd34a45a4d7f877411a2d5da9dbc":{
      "scriptId":"u5"},
    "7a3457d732b946838b453b4a7a1ebdba":{
      "scriptId":"u6"},
    "72504820efc345058994660305770843":{
      "scriptId":"u7"},
    "2ed9088e421d46a5aa56d928cd0c9241":{
      "scriptId":"u8"},
    "193d6495b10146a78949f1cb8cb09d60":{
      "scriptId":"u9"},
    "2420aca47f6545cfba08e6147e6a8f54":{
      "scriptId":"u10"},
    "55f0a99d2a81492483704db23bd54a01":{
      "scriptId":"u11"},
    "4cfa08b0dbee4dc0b197fa4e4d453d50":{
      "scriptId":"u12"},
    "f0cd48ea484643eb8d6b564d1bc7153f":{
      "scriptId":"u13"},
    "f02d58ef83dc4474906c440776a4fc22":{
      "scriptId":"u14"},
    "fc4b2ba6105940ef80bc82fd86968700":{
      "scriptId":"u15"},
    "7d3b42d36da0446b876afde0e691bc2b":{
      "scriptId":"u16"},
    "58dd62b474dc4c20837d8cd714969cef":{
      "scriptId":"u17"},
    "bd604b529aec488b81ddb37617293c08":{
      "scriptId":"u18"},
    "3e851f1c4e7b4809a25d0a1d8bd11db6":{
      "scriptId":"u19"},
    "2d7ac7367e3d49ce99c73b2639a1ca42":{
      "scriptId":"u20"},
    "65746a67035a46f0a3d5821f303ffdcb":{
      "scriptId":"u21"},
    "d6522633fec9444d82eae65f10a9c395":{
      "scriptId":"u22"},
    "a737f946347e40638d5e26e101a19aba":{
      "scriptId":"u23"},
    "ff63bcd8f88149709a33e049255c979b":{
      "scriptId":"u24"},
    "9193413482844d529265a054983beb94":{
      "scriptId":"u25"},
    "a5e9b47738aa4947a88c05f1cbcff4a0":{
      "scriptId":"u26"},
    "ce5507151e97446b8f0328b6d86264eb":{
      "scriptId":"u27"},
    "0e9efdd34cf84d0a8c1a8d166d4b0540":{
      "scriptId":"u28"},
    "9560dec3490d472d9960a83290d680c9":{
      "scriptId":"u29"},
    "6ebc27bff2bf44b3a24b911581670f1c":{
      "scriptId":"u30"},
    "acfd328d9e4a4addbf608d690ea084bf":{
      "scriptId":"u31"}}});